name: Build WSL2 Kernel

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  
  
env:
  TZ: America/Vancouver

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Initialization environment
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
    
    - name: Clone source code
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone https://github.com/microsoft/WSL2-Linux-Kernel -b linux-msft-wsl-5.10.y --single-branch WSL2-Linux-Kernel
        ln -sf /workdir/WSL2-Linux-Kernel $GITHUB_WORKSPACE/WSL2-Linux-Kernel
      
    - name: Load custom configuration
      run: |
        cp /config WSL2-Linux-Kernel/.config
            
    - name: Build
      run: |
        sudo apt install -y build-essential flex bison dwarves libssl-dev libelf-dev
        cd WSL2-Linux-Kernel
        make -j $(nproc)
      
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ${{ github.workspace }}/artifact/
